---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrationroute-webhook
  namespace: keip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrationroute-webhook
  template:
    metadata:
      labels:
        app: integrationroute-webhook
    spec:
      serviceAccountName: keip-controller-service
      containers:
        - name: webhook
          image: ghcr.io/codice/keip/webapp:0.18.0
          ports:
            - containerPort: 7080
              name: webhook-http
          env:
            - name: INTEGRATION_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: keip-controller-props
                  key: integration-image
            - name: LOG_LEVEL
              value: INFO
          resources:
            requests:
              cpu: "100m"
            limits:
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: integrationroute-webhook
  namespace: keip
spec:
  selector:
    app: integrationroute-webhook
  ports:
    - port: 80
      targetPort: webhook-http
