name: keip-integration

on:
  workflow_dispatch:
  pull_request:
    paths:
      - keip-integration/**
      - .github/workflows/keip-integration.yml
      - .github/workflows/scripts
  push:
    branches:
      - main
    paths:
      - keip-integration/**

env:
  WORKING_DIR: ./keip-integration
  JAVA_VERSION: 21
  GIT_TAG_PREFIX: keip-integration_v

permissions:
  contents: read

jobs:
  verify-versions:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: sh .github/workflows/scripts/verify_keip_integration_releasable.sh
        name: Verify keip-integration is in a state to be released on merge
  build:
    name: build image
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "temurin"
      - run: mvn --batch-mode --update-snapshots verify
        name: build image

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
    permissions:
      contents: write # create git tags
      packages: write # push docker images
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          REGISTRY=$(mvn help:evaluate -Dexpression=docker.registry -q -DforceStdout)
          IMAGE_NAME=$(mvn help:evaluate -Dexpression=image-name -q -DforceStdout)
          echo "REGISTRY=$REGISTRY" >> "$GITHUB_OUTPUT"
          echo "TAG_NAME=${{ env.GIT_TAG_PREFIX }}$VERSION" >> "$GITHUB_OUTPUT"
          echo "FULL_IMAGE_NAME=$REGISTRY/$IMAGE_NAME:$VERSION" >> "$GITHUB_OUTPUT"
          echo "LATEST_FULL_IMAGE_NAME=$REGISTRY/$IMAGE_NAME:latest" >> "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
        id: naming-selector
        name: generate names for artifacts

      - run: |
          git fetch --tags
          if git rev-parse -q --verify "refs/tags/${{ steps.naming-selector.outputs.TAG_NAME }}"; then
            # confirm image exists
            docker manifest inspect ${{ steps.naming-selector.outputs.FULL_IMAGE_NAME }}
          else
            echo "needs_release=true" >> $GITHUB_ENV
          fi
        name: check if release is needed

      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        if: env.needs_release == 'true'
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "temurin"
      - run: mvn --batch-mode --update-snapshots verify
        if: env.needs_release == 'true'
        name: build image

      - uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        if: env.needs_release == 'true'
        with:
          registry: ${{ steps.naming-selector.outputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker tag ${{ steps.naming-selector.outputs.FULL_IMAGE_NAME }} ${{ steps.naming-selector.outputs.LATEST_FULL_IMAGE_NAME }}
          docker push ${{ steps.naming-selector.outputs.FULL_IMAGE_NAME }}
          docker push ${{ steps.naming-selector.outputs.LATEST_FULL_IMAGE_NAME }}
        if: env.needs_release == 'true'

      - uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
        if: env.needs_release == 'true'
        id: tag_version
        with:
          custom_tag: ${{ steps.naming-selector.outputs.TAG_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # avoid v prefix before tag
          tag_prefix: ""
